import type { Metadata } from "next";
import inject from "@stylexjs/dev-runtime";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* @ts-ignore */
inject({
  classNamePrefix: "x",
  dev: true,
  test: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
